package com.example.todoapp.data.models

import androidx.room.Entity
import androidx.room.PrimaryKey
import com.example.todoapp.utils.Constants.DATABASE_TABLE

// Define the name of the database table for this entity
@Entity(tableName = DATABASE_TABLE)
data class ToDoTask(
    // Primary key auto-generated by Room
    @PrimaryKey(autoGenerate = true)
    val id: Int = 0, // Unique identifier for the task

    val title: String, // Title of the task

    val description: String, // Description of the task

    val priority: Priority // Priority of the task
)